### ISSUE TITLE
On Firefox: diagrams feature enabled - fails

### ISSUE THREAD

**Issue by mbeckerle** [asciidoctor/asciidoctor-browser-extension#310] opened 2019-11-06 02:00 UTC
Version 2.3.0

Firefox version 70.0.1 (64-bit)

If I install as a firefox add-on/extension, then I enable the diagrams feature by checking the box in the preferences/settings for this extension. Then when I try to view an asciidoc page that has a diagram, I get "Error

ReferenceError : AsciidoctorKroki is not defined"

This same thing viewing the same file, works fine on Chrome.

**Comment by Mogztter** [comment] 2019-11-06 09:08
Hi @mbeckerle 

I can reproduce this issue.
There were some specific issues with Firefox.
It should be fixed in https://github.com/asciidoctor/asciidoctor-browser-extension/pull/311

Could you please consider editing your review on the Firefox Add-ons ?
I don't think the extension deserves a 1/5 stars because a feature is not working at a given time on a specific browser: https://addons.mozilla.org/fr/firefox/addon/asciidoctorjs-live-preview/reviews/?score=1

Thanks

**Comment by mbeckerle** [comment] 2019-11-06 13:36
Deleted the bad review. When I can reinstall this plug in and it works again I will post 5 stars.

This is fantastically responsive. Much appreciated.

-mike
________________________________

**Comment by Mogztter** [comment] 2019-11-06 14:56
Thanks for reconsidering your review :+1: 

I'm making sure it's working on Chrome and Opera as well. Hopefully I will release a new version at the end of this week.

**Closed** 2019-11-09 10:08 UTC
Labels: :beetle:   bug, 🦊 Firefox

**Comment by Mogztter** [comment] 2019-11-09 13:08
I've published a new version 2.3.1.
Once it's approved by the Firefox team it will be available on https://addons.mozilla.org/

If you don't want to wait, you can install the xpi:

- Download the xpi file from the release page: https://github.com/asciidoctor/asciidoctor-browser-extension/releases/tag/v2.3.1
- Open `about:addons`
- Click `Install Add-on From File`

![install-file](https://user-images.githubusercontent.com/333276/68529021-52a75900-02fa-11ea-8e1f-78112058c6cb.png)


- Select the xpi file
- Enable Kroki from the extension options
- Enjoy!

![enjoy](https://user-images.githubusercontent.com/333276/68529008-30add680-02fa-11ea-94da-bd093792b92b.png)


Please note that for security reasons the following syntax does not work on Firefox:
```
plantuml::components.puml[]
```

See: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/302

**Comment by Mogztter** [comment] 2019-11-13 10:41
Version 2.3.1 is now available on the Firefox Add-ons website: https://addons.mozilla.org/firefox/addon/asciidoctorjs-live-preview/

@mbeckerle Could you please confirm that this issue is fixed?

**Comment by mbeckerle** [comment] 2019-11-13 14:28
Alas does not work for me. I installed, checked the box in preferences for allowing diagrams. Then view a file URL of an asciidoc file I have with diagrams in it. I get:

Error
ReferenceError : AsciidoctorKroki is not defined

**Comment by Mogztter** [comment] 2019-11-13 14:36
Are you sure that you are using the latest version?
Could you please go to `about:addons` and check the version:

![version](https://user-images.githubusercontent.com/333276/68773033-2574e680-062b-11ea-967f-55fbd6e797d0.png)

You might need to click "Check for Updates" and "Install update".

**Comment by mbeckerle** [comment] 2019-11-13 15:12
It says version 2.3.1.

**Comment by mbeckerle** [comment] 2019-11-13 15:14
Ah, a restart of Firefox, and now it is working.

**Comment by Mogztter** [comment] 2019-11-13 15:34
Great :ok_hand:
