### ISSUE TITLE
No longer loading online

### ISSUE THREAD

**Issue by doub** [asciidoctor/asciidoctor-browser-extension#323] opened 2020-03-27 15:51 UTC
Recently the plugin stopped working in my Chrome on Windows for online files. It still works for file:// URLs. I don't use it daily, but I think it stopped working around the last release (2.4.0, which is what I have now). The URL is of the form: http://server.company.com:8080/gitweb?p=path/to/repo.git;a=blob_plain;f=path/to/file.ad Now the file is always displayed as plain text. Since the URL is quite complex, I thought maybe it was because of that (it worked before though). I tried hosting the file on another server with a simple http://server/file.ad URL, but whatever MIME type I set the file gets downloaded by Chrome instead of being displayed.

**Comment by Mogztter** [comment] 2020-03-27 16:53
Hi Jérôme,

It's working for me on Windows using a GitHub URL:

![chrome-remote-ok](https://user-images.githubusercontent.com/333276/77779660-28f59100-7053-11ea-9850-9ad5571d5947.png)
![chrome-ext-version](https://user-images.githubusercontent.com/333276/77779664-298e2780-7053-11ea-9759-9f436eebe479.png)
![chrome-version](https://user-images.githubusercontent.com/333276/77779666-2a26be00-7053-11ea-9beb-3e58d5aaddb5.png)

> The URL is of the form: http://server.company.com:8080/gitweb?p=path/to/repo.git;a=blob_plain;f=path/to/file.ad Now the file is always displayed as plain text. 

Is your file available at a public URL?

Could you please check if you have any errors on the extension at chrome://extensions/ ? 

![errors](https://user-images.githubusercontent.com/333276/77779986-9bff0780-7053-11ea-967f-40d623e7ce84.png)

Could you also check the console while the DevTools are enabled?

Thanks!

**Comment by doub** [comment] 2020-03-27 19:20
That github URL does render properly. The problematic URL is on my company Intranet, and it's not accessible from the outside. I cloned the extension, and installed it locally in Chrome, and the commit that breaks the loading is 4c20ea05f4526fe8b43bf142585d9606e83f417b.

With the store-installed extension I don't have errors on the extension page, but I have an error and a bunch of warnings in the console:

```
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map
polyfill.js:1 Uncaught SyntaxError: Identifier 'getUILanguage' has already been declared
    at polyfill.js:1
(anonymous) @ polyfill.js:1
DevTools failed to parse SourceMap: chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/vendor/chartist.min.js.map
```

With the local copy of the extension, I have the same console errors as well as the following extension error:

![image](https://user-images.githubusercontent.com/117896/77792030-8c85bb80-705f-11ea-827d-2fa5cbeeb65a.png)

**Comment by Mogztter** [comment] 2020-03-27 22:45
I think it's most likely related to the AsciiDoc content itself.
I had to move the converter in the background script but now errors thrown during the conversion don't show, instead the raw content is displayed.

Uncaught exception during `XMLHttpRequest` might indicate the the converter failed to fetch an include or a resources declared in your AsciiDoc document.

The following error is also very strange:

```
polyfill.js:1 Uncaught SyntaxError: Identifier 'getUILanguage' has already been declared
    at polyfill.js:1
(anonymous) @ polyfill.js:1
```

Not sure if it's related or not...
I will try to publish a new version to display the error thrown by the converter from the background script to the content page.

**Comment by doub** [comment] 2020-03-27 23:15
I can checkout a branch if you want me to test things.

But I don't think the loading bug is related to content. It happens with the following minimal file:

```
= Title

Hello World.
```

**Comment by Mogztter** [comment] 2020-03-28 14:39
> I can checkout a branch if you want me to test things.

:+1: 

> But I don't think the loading bug is related to content. It happens with the following minimal file

Indeed, the root cause is probably somewhere else. Are you using additional resources?

![add-resources](https://user-images.githubusercontent.com/333276/77825537-3883e100-710a-11ea-8048-a1882f1e4e43.png)

Are you using Chrome 80+ ?

**Comment by Mogztter** [comment] 2020-03-28 15:19
Could you please try https://github.com/asciidoctor/asciidoctor-browser-extension/pull/324? Hopefully you should get an exception on the client side.

**Comment by doub** [comment] 2020-03-28 17:34
> Indeed, the root cause is probably somewhere else. Are you using additional resources?

No, all the same as your screenshot.

> Are you using Chrome 80+ ?

Yes, 80.0.3987.149.

> @doub Could you please try #324? Hopefully you should get an exception on the client side.

With that all that's shown (instead of the plain text .ad content) is:

> **Error**
> undefined : undefined`

With this in the console:

```
undefined
module.showError @ renderer.js:46
```

And this in the extension error page:

![image](https://user-images.githubusercontent.com/117896/77829483-493c5300-711a-11ea-9da2-7a45d2f3a9b8.png)

**Comment by Mogztter** [comment] 2020-03-28 18:16
In this case, could you please enable "Developer mode" (top right corner) and click on "Inspect views > Background page"

![developer-mode-background](https://user-images.githubusercontent.com/333276/77830384-48aab900-7128-11ea-836d-167d3b971a64.png)

It should open the DevTools on the background page. Then refresh the tab where your AsciiDoc file is displayed and check out the console panel in the DevTools. Hopefully you should see a more meaningful stack trace / error message.

**Comment by doub** [comment] 2020-03-28 21:32
There's an error every second or two. Each looks somewhat like this:
```
GET http://server.company.com:1234/gitweb?p=path/to/repo.git;a=blob_plain;f=path/to/file.ad?_=1585430869139 404 (Not Found)
(anonymous) @ converter.js:24
executeRequest @ converter.js:7
module.fetchAndConvert @ converter.js:82
(anonymous) @ background.js:55
```

The server does indeed reply with a 404 to that URL. The page I tried to open is that URL minus the `?_=1585430869139` part at the end.

**Comment by doub** [comment] 2020-03-28 21:35
I forgot to mention that the appended number increases at each request, here's an extract:
- 1585431249937
- 1585431251938
- 1585431253937
- 1585431255937
- 1585431257938
- 1585431259938
- 1585431261938

**Comment by Mogztter** [comment] 2020-03-28 22:36
The suffix is automatically appended to avoid caching (with a timestamp) when the extension reload the page.
The main issue is that your URL already contains URI parameters so the suffix should be `&_=1585430869139`. We might want to replace this suffix with the request header `Cache-Control: no-cache`.

Please note that you can disable the "Poll for changes" feature on remote files:

![poll-changes](https://user-images.githubusercontent.com/333276/77835323-d8159380-714b-11ea-902d-84bbf69bc1f4.png)

I also need to catch the error if the initial request throws an exception.

**Comment by Mogztter** [comment] 2020-03-29 10:13
@doub I've changed a few things in #324

- Use `Cache-Control` header instead of the suffix `&_=${${new Date().getTime()}}` to disable cache
- If the initial request returns an error (status code is not 200) then we do not update the page but we will still poll for changes (if enabled) in case the failure was temporary
- Catch exception during the initial request

Could you please fetch these changes and give it another try?

**Comment by doub** [comment] 2020-03-29 20:02
This looks like it's working for me, with or without the auto-reload.

**Comment by Mogztter** [comment] 2020-03-29 21:06
> This looks like it's working for me, with or without the auto-reload.

That's a good news 👍 
I will cleanup the code, review it, merge it and publish a new version in the next few days. Thanks for the testing.

**Comment by Mogztter** [comment] 2020-04-13 16:54
Fixed in https://github.com/asciidoctor/asciidoctor-browser-extension/commit/dde7fea23890b7527779d9072ee4345e76b1602e

**Closed by Mogztter** 2020-04-13 16:54 UTC
Labels: 👀 investigating
