### ISSUE TITLE
XMLHttpRequest at file from origin 'null' has been blocked by CORS policy

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor-browser-extension#316] opened 2020-02-11 09:42 UTC
Hello.
Chromium: 80.0.3987.87 (Official Build) (64-bit)
Extension stopped to work.
I got at console:
```
Access to XMLHttpRequest at 'file:///D:/docs/conf.adoc' from origin 'null'
has been blocked by CORS policy: Cross origin requests are only supported
for protocol schemes: http, data, chrome, chrome-extension, brave, https.
```
It seems that it's the new feature of the latest Chrome...

**Comment by sindzicat** [comment] 2020-02-11 09:49
These docs may be useful: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches/

**Comment by sindzicat** [comment] 2020-02-11 09:53
I tried to run browser with flag `--disable-web-security`. Now extension works, but I also get the following message on the top of web page:
```
You are using an unsupported command-line flag: --disable-web-security.
Stability and security will suffer.
```
![image](https://user-images.githubusercontent.com/33900895/74226280-58338700-4ccd-11ea-8cb6-d92946a788bf.png)

So this is definitely CORS.

I will try to find anything better...

**Comment by sindzicat** [comment] 2020-02-11 10:02
I tried flag
```
chrome://flags/#out-of-blink-cors
```
Found here: https://support.google.com/chrome/thread/11089651?hl=en&msgid=11328844

This is helped me, but this key worked on the third try.

**Comment by sindzicat** [comment] 2020-02-11 10:05
Maybe, this news will be helpfull: https://security.googleblog.com/2019/10/no-more-mixed-messages-about-https_3.html

**Comment by sindzicat** [comment] 2020-02-11 10:11
In general, the extension works now, but the page no longer refreshes automatically.

**Comment by sindzicat** [comment] 2020-02-11 10:21
![image](https://user-images.githubusercontent.com/33900895/74228350-566bc280-4cd1-11ea-9ea5-4cd0032d1e67.png)

**Comment by sindzicat** [comment] 2020-02-11 10:23
Sorry, page updates automatically. I was wrong.

**Comment by Mogztter** [comment] 2020-02-11 12:29
I think it's the same issue as https://github.com/asciidoctor/asciidoctor-browser-extension/issues/315 no?

**Comment by sindzicat** [comment] 2020-02-11 13:25
Sorry, really don't know.

**Comment by Mogztter** [comment] 2020-02-11 13:36
This link https://www.chromium.org/Home/chromium-security/extension-content-script-fetches/ is really useful thanks!
I might have found a solution to workaround this security constraint :+1:

**Comment by Mogztter** [comment] 2020-02-14 10:02
fixed in https://github.com/asciidoctor/asciidoctor-browser-extension/commit/4c20ea05f4526fe8b43bf142585d9606e83f417b

**Closed by Mogztter** 2020-02-14 10:02 UTC

**Comment by sindzicat** [comment] 2020-02-17 11:32
Extension isn't updated on Google Web Store yet...

**Comment by Mogztter** [comment] 2020-02-17 12:10
Nope... Chrome added extra steps and manual review on the Chrome Web Store, perfect timing... So the new version is pending review :angry:

**Comment by sindzicat** [comment] 2020-02-17 12:14
¯\_(ツ)_/¯

**Comment by Mogztter** [comment] 2020-02-17 12:24
> We have reached out to developers whose extensions are on the allowlist.
https://www.chromium.org/Home/chromium-security/extension-content-script-fetches/

And by the way, I'm still waiting to receive a notification from the Chrome team to warn me about this change :laughing:

**Comment by Mogztter** [comment] 2020-02-17 17:44
@sindzicat It should be available now!

**Comment by sindzicat** [comment] 2020-02-17 17:56
Yes, it it. Many thanks! =(^_^)=

**Comment by Alex-Tarsisius** [comment] 2020-06-03 11:52
A notification appears:
Access to script at 'file: /// D: / Create%20website%202/Bikin%20Kalender%202/Bikin%20Kalender%202.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

please help me how to solve the problem ..

**Comment by Mogztter** [comment] 2020-06-03 13:02
The error seems unrelated... what is `file:///D:/Create%20website%202/Bikin%20Kalender%202/Bikin%20Kalender%202.js`?

> please help me how to solve the problem ..

You should give us more context if you want help, please describe what your are trying to do and add a sample AsciiDoc to reproduce this issue.
Also provide informations about your environment, which browser are your using? which version? which operating system? are your trying to preview a local from your local file system? from a shared network? ...

**Comment by MANOJ8505** [comment] 2020-07-21 03:44
I 'm tring lot of thiks but not fix issue pls hepl.
Access to XMLHttpRequest at 'localhost:3000/admin/saveAdmin' from origin 'http://localhost:3000' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
register.js:47 Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:81)
xhr.js:172 POST localhost:3000/admin/saveAdmin net::ERR_FAILED

**Comment by Mogztter** [comment] 2020-07-21 05:58
I don't think this error is related to the Asciidoctor browser extension.

You most likely need to configure your server to allow https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS between the two domains.

**Comment by pawan-git7979** [comment] 2020-09-14 16:53
> I tried flag
> 
> ```
> chrome://flags/#out-of-blink-cors
> ```
> 
> Found here: https://support.google.com/chrome/thread/11089651?hl=en&msgid=11328844
> 
> This is helped me, but this key worked on the third try.

Where we have to type this command, in terminal or Google console.

**Comment by Mogztter** [comment] 2020-09-14 18:33
> Where we have to type this command, in terminal or Google console.

I would not recommend modifying this setting.
The error `XMLHttpRequest at file from origin 'null' has been blocked by CORS policy` is generic and the root cause is probably not related to this specific issue.
To answer your question, you need to type `chrome://flags/#out-of-blink-cors` in the URL bar. Please note that this option has been renamed. Ìn Chrome 85, the flag is available at `chrome://flags/#cors-for-content-scripts`

> CORS for content scripts
Prevent content scripts of Chrome Extensions from bypassing CORS. For more information about the allowlist and the changes to the security model of content scripts, please see: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches – Mac, Windows, Linux, Chrome OS

I've locked this issue to avoid off-topic. This issue was about an incompatibility between Chrome 80 and the Asciidoctor Browser Extension. This issue is now fixed.
