### ISSUE TITLE
Opera Addons list version 2.4.0 as the latest update

### ISSUE THREAD

**Issue by mkgl** [asciidoctor/asciidoctor-browser-extension#451] opened 2020-11-19 13:35 UTC
Hi there, 👋 

Bitbucket URLs on branches typically look like `<host>/.../repos/my-repo/raw/path/to/FILE.adoc?at=refs%2Fheads%2Fmy-branch`

The live preview doesn't kick in for such URLs, despite having the expected file extension.
Workaround: it's possible to fool the matching by adding a query-param `&foobar.adoc` or even URL fragment `#foobar.adoc`.

Shouldn't the Asciidoctor.js Live Preview resolve file extension in the URL path segment?

**Comment by Mogztter** [comment] 2020-11-19 17:09
Hi @mkgl 

It should, we are using the following matches:

**Comment by mkgl** [comment] 2020-11-20 16:32
Hi @Mogztter,

Thank you for the swift reply, I should have specified browser indeed. 🙂
I'm on Opera 72, extension version 2.4.0. I assumed Chrome be affected too, but it actually worked. And I further realized I got version 2.6.1 there. So the issue seems to be that [Opera Addons](https://addons.opera.com/fr/extensions/details/asciidoctorjs-live-preview/) list version 2.4.0 as the latest update.

Below is what I ran through before I figured this out:

> Here's a couple public URLs (using the asciidoc extension there, but same effect):
> * https://git.magnolia-cms.com/users/mgeljic/repos/vaadin-cafe-finder-demo/raw/README.asciidoc (works)
> * https://git.magnolia-cms.com/users/mgeljic/repos/vaadin-cafe-finder-demo/raw/README.asciidoc?at=refs%2Fheads%2Fmaster (doesn't)
> 
> There's an error from the extension's dev-tools console; converter.js appends a second question-mark to the URL (and Bitbucket yields 404 to that).
> 
> ```
> GET https://git.magnolia-cms.com/users/mgeljic/repos/vaadin-cafe-finder-demo/raw/README.asciidoc?at=refs%2Fheads%2Fmaster?_=1605887984681 404
> _generated_background_page.html:1 Uncaught (in promise) 
> XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, onreadystatechange: ƒ, …}
> ...
> ```
>
> `converter.js` used to do this:
> ```
> // disable cache
> request.open('GET', `${url}?_=${new Date().getTime()}`, true)
> request.send(null)
> ```

I'll rephrase the issue if I may.

Cheers,
Mika

**Comment by Mogztter** [comment] 2020-11-20 17:47
Thanks for clarifying!
I think this is actually a duplicate of https://github.com/asciidoctor/asciidoctor-browser-extension/issues/323 fixed in version 2.5.0 and up.

I have submitted version 2.6.1 to https://addons.opera.com 6 months ago!

> Asciidoctor.js Live Preview v2.6.1 was submitted. Awaiting moderation.
> Jun 16, 2020 7:59:35 PM UTC

In general, it takes a few days to get approved and I assumed that the new version will be available soon enough.
But I didn't check and forgot about it.

For reference, the new version is available in Opera Developer and Opera Next:

> Status has changed for Asciidoctor.js Live Preview
> Asciidoctor.js Live Preview v2.6.1 on Opera Developer: Published.
> Asciidoctor.js Live Preview v2.6.1 on Opera Next: Published.

The last message was:

> Moderator's note:
> Your extension needs to be manually reviewed and moderated before it can be added to Opera Stable. It is currently only viewable and available for download in Opera Developer and Opera Beta.

I added a reply asking for news.

**Comment by mkgl** [comment] 2020-11-20 22:46
Brilliant, didn't take long this time, Opera Addons now list 2.6.1. Thanks a lot!

**Comment by Mogztter** [comment] 2020-11-21 08:38
Yay! 🎉
I got an email confirming that 2.6.1 is now available on Opera.
My initial submission must have slipped through because most of the time the Opera team is really quick to respond (as you can see here).

Can you confirm that the bug is indeed fixed on Opera with the latest version (2.6.1)? If so, we can close this issue 😉

**Closed** 2020-11-21 08:39 UTC
Labels: :o: Opera, :upside_down_face: upstream, 🐞 bug
